config/routes.php
<?php
/**
 * Routes configuration.
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * It's loaded within the context of `Application::routes()` method which
 * receives a `RouteBuilder` instance `$routes` as method argument.
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Routing\Route\DashedRoute;
use Cake\Routing\RouteBuilder;

/*
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 */
/** @var \Cake\Routing\RouteBuilder $routes */
$routes->setRouteClass(DashedRoute::class);

$routes->scope('/', function (RouteBuilder $builder) {
    /*
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, templates/Pages/home.php)...
     */
    $builder->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);

    /*
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $builder->connect('/pages/*', 'Pages::display');
    // All routes here will be prefixed with `/admin`
    // And have the prefix => admin route element added.

    // bulk edit pages
    $builder->connect('/legislators/bulkedit/{sessionId}/{chamber}', array('controller' => 'Legislators', 'action' => 'bulkedit'));
    $builder->connect('/people/bulkedit/{sessionId}/{chamber}', array('controller' => 'People', 'action' => 'bulkedit'));
    $builder->connect('/ratings/bulkedit/{sessionId}/{chamber}', array('controller' => 'Ratings', 'action' => 'bulkedit'));
    $builder->connect('/rating-criterias/bulkedit/{sessionId}', array('controller' => 'RatingCriterias', 'action' => 'bulkedit'));
    $builder->connect('/rating-criterias/bulkedit/{sessionId}/{ratingId}', array('controller' => 'RatingCriterias', 'action' => 'bulkedit'));
    $builder->connect('/records/bulkedit/{ratingId}', array('controller' => 'Records', 'action' => 'bulkedit'));
    $builder->connect('/scores/bulkedit/{sessionId}/{chamber}/{orgId}', array('controller' => 'Scores', 'action' => 'bulkedit'));

    // public user pages
    $builder->connect('/forgot-password', array('controller' => 'users', 'action' => 'forgotPassword'));
    $builder->connect('/reset-password', array('controller' => 'users', 'action' => 'resetPassword'));
    $builder->connect('/login', array('controller' => 'users', 'action' => 'login'));
    $builder->connect('/logout', array('controller' => 'users', 'action' => 'logout'));
    $builder->connect('/signup', array('controller' => 'users', 'action' => 'signup'));
    $builder->connect('/finish-signup', array('controller' => 'users', 'action' => 'finishSignup'));

    // public account pages
    $builder->connect('/invite/*', array('controller' => 'accounts', 'action' => 'invite'));
    $builder->connect('/verify/*', array('controller' => 'accounts', 'action' => 'verify'));

    // public policy pages
    $builder->connect('/terms', array('controller' => 'pages', 'action' => 'terms'));
    $builder->connect('/privacy-policy', array('controller' => 'pages', 'action' => 'privacyPolicy'));
    $builder->connect('/cookie-policy', array('controller' => 'pages', 'action' => 'cookiePolicy'));

    // app-specific pages

    // password protected

    // jpm functions
    $builder->connect('/jpm/invalidate', array('controller' => 'Pages', 'action' => 'cacheInvalidate'));

    /*
     * Connect catchall routes for all controllers.
     *
     * The `fallbacks` method is a shortcut for
     *
     * ```
     * $builder->connect('/:controller', ['action' => 'index']);
     * $builder->connect('/:controller/:action/*', []);
     * ```
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $builder->fallbacks();
});

/*
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * $routes->scope('/api', function (RouteBuilder $builder) {
 *     // No $builder->applyMiddleware() here.
 *
 *     // Parse specified extensions from URLs
 *     // $builder->setExtensions(['json', 'xml']);
 *
 *     // Connect API actions here.
 * });
 * ```
 */

$routes->prefix('admin', function (RouteBuilder $routes) {
    // All routes here will be prefixed with `/admin`, and
    // have the `'prefix' => 'Admin'` route element added that
    // will be required when generating URLs for these routes
    $routes->fallbacks(DashedRoute::class);
});

$routes->prefix('api', function (RouteBuilder $routes) {
    $routes->setExtensions(['json', 'xml']);

    $routes->resources('action-types');
    $routes->resources('actions');
    $routes->resources('address-types');
    $routes->resources('addresses');
    $routes->resources('chambers');
    $routes->resources('grades');
    $routes->resources('legislative-sessions');
    $routes->resources('legislators');
    $routes->resources('organizations');


    // All routes here will be prefixed with `/admin`, and
    // have the `'prefix' => 'Admin'` route element added that
    // will be required when generating URLs for these routes
    $routes->fallbacks(DashedRoute::class);
});

$routes->setExtensions(['csv']);

src/Model/Table/BillsTable.php
<?php
declare(strict_types=1);

namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Bills Model
 *
 * @property \App\Model\Table\TenantsTable&\Cake\ORM\Association\BelongsTo $Tenants
 * @property \App\Model\Table\LegislativeSessionsTable&\Cake\ORM\Association\BelongsTo $LegislativeSessions
 * @property \App\Model\Table\ChambersTable&\Cake\ORM\Association\BelongsTo $FiledChamber
 * @property \App\Model\Table\ChambersTable&\Cake\ORM\Association\BelongsTo $CurrentChamber
 * @property \App\Model\Table\BillEnumsTable&\Cake\ORM\Association\BelongsTo $CurrentBillStage
 * @property \App\Model\Table\BillEnumsTable&\Cake\ORM\Association\BelongsTo $CurrentBillStatus
 * @property \App\Model\Table\BillEnumsTable&\Cake\ORM\Association\BelongsTo $CurrentBillCta
 * @property \App\Model\Table\BillEnumsTable&\Cake\ORM\Association\BelongsTo $currentBillProgress
 * @property \App\Model\Table\BillEnumsTable&\Cake\ORM\Association\BelongsTo $CurrentBillPhaseIcon
 * @property \App\Model\Table\BillEnumsTable&\Cake\ORM\Association\BelongsTo $CurrentBillRatingIcon
 * @property \App\Model\Table\RatingsTable&\Cake\ORM\Association\BelongsTo $HouseRating
 * @property \App\Model\Table\RatingsTable&\Cake\ORM\Association\BelongsTo $SenateRating
 *
 * @method \App\Model\Entity\Bill newEmptyEntity()
 * @method \App\Model\Entity\Bill newEntity(array $data, array $options = [])
 * @method \App\Model\Entity\Bill[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Bill get($primaryKey, $options = [])
 * @method \App\Model\Entity\Bill findOrCreate($search, ?callable $callback = null, $options = [])
 * @method \App\Model\Entity\Bill patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Bill[] patchEntities(iterable $entities, array $data, array $options = [])
 * @method \App\Model\Entity\Bill|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Bill saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Bill[]|\Cake\Datasource\ResultSetInterface|false saveMany(iterable $entities, $options = [])
 * @method \App\Model\Entity\Bill[]|\Cake\Datasource\ResultSetInterface saveManyOrFail(iterable $entities, $options = [])
 * @method \App\Model\Entity\Bill[]|\Cake\Datasource\ResultSetInterface|false deleteMany(iterable $entities, $options = [])
 * @method \App\Model\Entity\Bill[]|\Cake\Datasource\ResultSetInterface deleteManyOrFail(iterable $entities, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class BillsTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     */
    public function initialize(array $config): void
    {
        parent::initialize($config);

        $this->setTable('bills');
        $this->setDisplayField('bill_number');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');
        $this->addBehavior('Tenant');

        $this->belongsTo('Tenants', [
            'foreignKey' => 'tenant_id',
            'joinType' => 'INNER',
        ]);
        $this->belongsTo('LegislativeSessions', [
            'foreignKey' => 'legislative_session_id',
            'joinType' => 'INNER',
        ]);

        // Add associations for 'current' fields mapping to BillEnums
        $this->belongsTo('CurrentBillStage', [
            'className' => 'BillEnums',
            'foreignKey' => 'current_bill_stage_id',
            'conditions' => ['CurrentBillStage.type' => 'stage'],
            'joinType' => 'LEFT',
        ]);

        $this->belongsTo('CurrentBillStatus', [
            'className' => 'BillEnums',
            'foreignKey' => 'current_bill_status_id',
            'conditions' => ['CurrentBillStatus.type' => 'status'],
            'joinType' => 'LEFT',
        ]);

        $this->belongsTo('CurrentBillCta', [
            'className' => 'BillEnums',
            'foreignKey' => 'current_bill_cta_id',
            'conditions' => ['CurrentBillCta.type' => 'cta'],
            'joinType' => 'LEFT',
        ]);

        $this->belongsTo('CurrentBillProgress', [
            'className' => 'BillEnums',
            'foreignKey' => 'current_bill_progress_id',
            'conditions' => ['CurrentBillProgress.type' => 'progress'],
            'joinType' => 'LEFT',
        ]);

        $this->belongsTo('CurrentBillPhaseIcon', [
            'className' => 'BillEnums',
            'foreignKey' => 'current_bill_phase_icon_id',
            'conditions' => ['CurrentBillPhaseIcon.type' => 'phase-icon'],
            'joinType' => 'LEFT',
        ]);

        $this->belongsTo('CurrentBillRatingIcon', [
            'className' => 'BillEnums',
            'foreignKey' => 'current_bill_rating_icon_id',
            'conditions' => ['CurrentBillRatingIcon.type' => 'rating-icon'],
            'joinType' => 'LEFT',
        ]);

        // Chambers associations
        $this->belongsTo('FiledChamber', [
            'className' => 'Chambers',
            'foreignKey' => 'filed_chamber_id',
            'joinType' => 'LEFT',
        ]);

        $this->belongsTo('CurrentChamber', [
            'className' => 'Chambers',
            'foreignKey' => 'current_chamber_id',
            'joinType' => 'LEFT',
        ]);

        // Ratings associations
        $this->belongsTo('HouseRating', [
            'className' => 'Ratings',
            'foreignKey' => 'house_rating_id',
            'joinType' => 'LEFT',
        ]);

        $this->belongsTo('SenateRating', [
            'className' => 'Ratings',
            'foreignKey' => 'senate_rating_id',
            'joinType' => 'LEFT',
        ]);

        // LegiScan Bills association
        $this->belongsTo('LegiscanBill', [
            'className' => 'LegiscanBills',
            'foreignKey' => 'legiscan_bill_id',
            'joinType' => 'LEFT',
        ]);

        $this->belongsTo('Uploads', [
            'foreignKey' => 'upload_id',
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     */
    public function validationDefault(Validator $validator): Validator
    {
        $validator
            ->uuid('legislative_session_id')
            ->notEmptyString('legislative_session_id');

        $validator
            ->uuid('filed_chamber_id')
            ->notEmptyFile('filed_chamber_id');

        $validator
            ->scalar('bill_number')
            ->maxLength('bill_number', 45)
            ->requirePresence('bill_number', 'create')
            ->notEmptyString('bill_number');

        $validator
            ->scalar('official_title')
            ->maxLength('official_title', 255)
            ->requirePresence('official_title', 'create')
            ->notEmptyString('official_title');

        $validator
            ->scalar('explainer_title')
            ->maxLength('explainer_title', 255)
            ->requirePresence('explainer_title', 'create')
            ->notEmptyString('explainer_title');

        $validator
            ->scalar('description')
            ->maxLength('description', 4294967295)
            ->allowEmptyString('description');

        $validator
            ->scalar('notes')
            ->maxLength('notes', 4294967295)
            ->allowEmptyString('notes');

        $validator
            ->scalar('sponsors')
            ->maxLength('sponsors', 255)
            ->allowEmptyString('sponsors');

        $validator
            ->nonNegativeInteger('legiscan_bill_id')
            ->allowEmptyString('legiscan_bill_id');

        $validator
            ->uuid('current_chamber_id')
            ->allowEmptyString('current_chamber_id');

        $validator
            ->uuid('current_bill_stage_id')
            ->allowEmptyString('current_bill_stage_id');

        $validator
            ->uuid('current_bill_status_id')
            ->allowEmptyString('current_bill_status_id');

        $validator
            ->uuid('current_bill_cta_id')
            ->allowEmptyString('current_bill_cta_id');

        $validator
            ->add('current_bill_cta_url', 'validUrl', [
                'rule' => ['custom', '/^(https?:\/\/)([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$/i'],
                'message' => 'The provided URL must start with http or https and be a valid URL.'
            ])
            ->allowEmptyString('current_bill_cta_url');

        $validator
            ->uuid('current_bill_progress_id')
            ->allowEmptyString('current_bill_progress_id');

        $validator
            ->uuid('current_bill_phase_icon_id')
            ->allowEmptyString('current_bill_phase_icon_id');

        $validator
            ->uuid('current_bill_rating_icon_id')
            ->allowEmptyString('current_bill_rating_icon_id');

        $validator
            ->uuid('house_rating_id')
            ->allowEmptyString('house_rating_id');

        $validator
            ->scalar('house_rating_votes')
            ->maxLength('house_rating_votes', 4294967295)
            ->allowEmptyString('house_rating_votes');

        $validator
            ->uuid('senate_rating_id')
            ->allowEmptyString('senate_rating_id');

        $validator
            ->scalar('senate_rating_votes')
            ->maxLength('senate_rating_votes', 4294967295)
            ->allowEmptyString('senate_rating_votes');

        $validator
            ->uuid('upload_id')
            ->allowEmptyString('upload_id');

        $validator
            ->scalar('slug')
            ->maxLength('slug', 255)
            ->requirePresence('slug', 'create')
            ->notEmptyString('slug');

        $validator
            ->boolean('is_enabled')
            ->notEmptyString('is_enabled');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating

templates/Bills/add.php
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Bill $bill
 */
?>
<?= $this->Html->script('View/Bills/add_edit.js?v=20240913') ?>
<div class="bills form">
    <div class="row">
        <div class="col-lg-12">
            <div class="page-header">
                <h1><?= __('Add Bill') ?></h1>
            </div>
        </div>
        <!-- end col lg 12 -->
    </div>
    <!-- end row -->
    <div class="row">
        <div class="col-md-3">
            <div class="actions">
                <div class="card">
                    <div class="card-header">Actions</div>
                    <div class="card-body">
                        <ul class="nav nav-pills flex-column">
                            <li>
                                <?= $this->Html->link(__('<span class="octicon octicon-list-unordered"></span>&nbsp;&nbsp;List Bills
                                ')
                                    , ['action' => 'index']
                                    , ['escape' => false, 'class' => 'nav-link'])
                                ?>
                            </li>
                        </ul>
                    </div>
                    <!-- end body -->
                </div>
                <!-- end panel -->
            </div>
            <!-- end actions -->
        </div>
        <!-- end col md 3 -->
        <div class="col-md-9">
            <?php echo $this->element('Bills/add_edit'); ?>
        </div>
        <!-- end col md 9 -->
    </div>
    <!-- end row -->
</div>
<!-- end containing of content -->

templates/Bills/edit.php
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Bill $bill
 */
?>
<?= $this->Html->script('View/Bills/add_edit.js?v=20240913') ?>
<div class="bills form">
    <div class="row">
        <div class="col-lg-12">
            <div class="page-header">
                <h1><?= __('Edit Bill') ?></h1>
            </div>
        </div>
        <!-- end col lg 12 -->
    </div>
    <!-- end row -->
    <div class="row">
        <div class="col-md-3">
            <div class="actions">
                <div class="card">
                    <div class="card-header">Actions</div>
                    <div class="card-body">
                        <ul class="nav nav-pills flex-column">
                            <li>
                                <?= $this->Html->link(__('<span class="octicon octicon-list-unordered"></span>&nbsp;&nbsp;List Bills
                                ')
                                    , ['action' => 'index']
                                    , ['escape' => false, 'class' => 'nav-link'])
                                ?>
                            </li>
                        </ul>
                    </div>
                    <!-- end body -->
                </div>
                <!-- end panel -->
            </div>
            <!-- end actions -->
        </div>
        <!-- end col md 3 -->
        <div class="col-md-9">
            <?php echo $this->element('Bills/add_edit'); ?>
        </div>
        <!-- end col md 9 -->
    </div>
    <!-- end row -->
</div>
<!-- end containing of content -->

templates/Bills/view.php
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Bill $bill
 */
use Cake\Core\Configure;
?>
<style>
.upload-image {
    width: 50%;
    /* Set a classic checkerboard grid as background */
    background-image: linear-gradient(45deg, #ccc 25%, transparent 25%, transparent 75%, #ccc 75%, #ccc),
                      linear-gradient(45deg, #ccc 25%, transparent 25%, transparent 75%, #ccc 75%, #ccc);
    background-size: 20px 20px; /* Size of the checkerboard squares */
    background-position: 0 0, 10px 10px; /* Offset second layer for grid alignment */
}
</style>
<div class="bills view">
    <div class="row">
        <div class="col-lg-12">
            <div class="page-header">
                <h1><?= h($bill->name) ?></h1>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="actions">
                <div class="card">
                    <div class="card-header">Actions</div>
                    <div class="card-body">
                        <ul class="nav nav-pills flex-column">
                            <li>
                                <?=
                                $this->Html->link(__('<span class="octicon octicon-pencil"></span>
                                Edit Bill')
                                    , ['action' => 'edit', $bill->id]
                                    , ['escape' => false, 'class' => 'nav-link']
                                )
                                ?>
                            </li>
                            <li>
                                <?=
                                $this->Html->link(__('<span class="octicon octicon-list-unordered"></span>
                                List Bills')
                                    , ['action' => 'index']
                                    , ['escape' => false, 'class' => 'nav-link']
                                )
                                ?>
                            </li>
                            <li>
                                <?=
                                $this->Html->link(__('<span class="octicon octicon-plus"></span>
                                New Bill')
                                    , ['action' => 'add']
                                    , ['escape' => false, 'class' => 'nav-link']
                                )
                                ?>
                            </li>
                        </ul>
                    </div>
                    <!-- end body -->
                </div>
                <!-- end panel -->
            </div>
            <!-- end actions -->
        </div>
        <!-- end col md 3 -->
        <div class="col-md-9">
            <table class="table table-striped table-sm">

                <tr>
                    <th scope="row" style="width: 200px"><?= __('Legislative Session') ?></th>
                    <td><?= $bill->has('legislative_session') ?
                            $this->Html->link($bill->legislative_session
                                ->name, ['controller' => 'LegislativeSessions',
                                'action' => 'view', $bill->legislative_session
                                    ->id]) : '' ?>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><?= __('Filed Chamber') ?></th>
                    <td><?= $bill->has('filed_chamber') ?
                            $this->Html->link($bill->filed_chamber
                                ->name, ['controller' => 'Chambers',
                                'action' => 'view', $bill->filed_chamber
                                    ->id]) : '' ?>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><?= __('Bill Number') ?></th>
                    <td><?= h($bill->bill_number) ?></td>
                </tr>
                <tr>
                    <th scope="row"><?= __('Official Title') ?></th>
                    <td><?= h($bill->official_title) ?></td>
                </tr>
                <tr>
                    <th scope="row"><?= __('Explainer Title') ?></th>
                    <td><?= h($bill->explainer_title) ?></td>
                </tr>
                <tr>
                    <th scope="row"><?= __('Sponsors') ?></th>
                    <td><?= h($bill->sponsors) ?></td>
                </tr>
                <?php
                $fields = [
                    'current_chamber' => ['Chambers', 'Current Chamber', 'No Chamber'],
                    'current_bill_stage' => ['BillEnums', 'Current Bill Stage', 'No Stage'],
                    'current_bill_status' => ['BillEnums', 'Current Bill Status', 'No Status'],
                    'current_bill_progres' => ['BillEnums', 'Current Bill Progress', 'No Progress'],
                    'current_bill_phase_icon' => ['BillEnums', 'Current Bill Process Phase Icon', 'No Phase Icon'],
                    'current_bill_rating_icon' => ['BillEnums', 'Current Bill Rating Icon', 'No Rating Icon'],
                    'current_bill_ctum' => ['BillEnums', 'Current Bill CTA', 'No Call to Action'],
                ];

                foreach ($fields as $field => $info) {
                    [$controller, $label, $noDataText] = $info;
                    ?>
                    <tr>
                        <th scope="row"><?= __($label) ?></th>
                        <td>
                            <?= $bill->has($field) ?
                                $this->Html->link($bill->{$field}->name, ['controller' => $controller, 'action' => 'view', $bill->{$field}->id]) :
                                $noDataText ?>
                        </td>
                    </tr>
                <?php } ?>
                <tr>
                    <th scope="row"><?= __('Current Bill CTA URL') ?></th>
                    <td><?= h($bill->current_bill_cta_url) ?></td>
                </tr>
                <tr>
                    <th scope="row"><?= __('LegiScan Bill') ?></th>
                    <td>
                        <?php
                        if ($bill->legiscan_bill_id > 0) {
                            ?>
                            <a href="<?php echo $bill->legiscan_bill->legiscan_url; ?>" target="_blank">
                                <?php echo $this->LegiscanBill->getBillName($bill->legiscan_bill->bill_number) ?>
                                <span class="octicon octicon-link-external"></span>
                            </a>
                            <?php
                        } else {
                            echo 'No LegiScan Bill';
                        }
                        ?>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><?= __('House Rating') ?></th>
                    <td><?= $bill->has('house_rating') ?
                            $this->Html->link($bill->house_rating
                                ->name, ['controller' => 'Ratings',
                                'action' => 'view', $bill->house_rating
                                    ->id]) : '' ?>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><?= __('House Rating Votes') ?></th>
                    <td><?php echo $bill->house_rating_votes; ?></td>
                </tr>
                <tr>
                    <th scope="row"><?= __('Senate Rating') ?></th>
                    <td><?= $bill->has('senate_rating') ?
                            $this->Html->link($bill->senate_rating
                                ->name, ['controller' => 'Ratings',
                                'action' => 'view', $bill->senate_rating
                                    ->id]) : '' ?>
                    </td>
                </tr>
                <tr>
                    <th scope="row"><?= __('Senate Rating Votes') ?></th>
                    <td><?php echo $bill->senate_rating_votes; ?></td>
                </tr>
                <tr>
                    <th scope="row"><?= __('Slug') ?></th>
                    <td><?= h($bill->slug) ?></td>
                </tr>
                <tr>
                    <th scope="row"><?= __('Visibility') ?></th>
                    <td><?= $this->Visibility->display_text($bill->is_enabled); ?></td>
                </tr>
                <tr>
                    <th scope="row"><?= __('Legiscan Bill Id') ?></th>
                    <td><?= $this->Number->format($bill->legiscan_bill_id) ?></td>
                </tr>
                <tr>
                    <th scope="row"><?= __('Feature Image') ?></th>
                    <td>
                        <?php
                            $hasCurrentUploadSrc = !empty($bill->upload->path);
                            $currentUploadSrc = $hasCurrentUploadSrc ? Configure::read('App.r2_base_url') . '/' . $bill->upload->path : null;
                            if ($hasCurrentUploadSrc) {
                                echo $this->Html->image($currentUploadSrc, ['class' => 'upload-image img-fluid']);
                            }
                        ?>
                    </td>
                </tr>
            </table>

        </div>
        <!-- end col md 9 -->
    </div>
    <!-- end row -->
</div>

    